services:

  backend:
    build:
      context: .
      dockerfile: DockerFile

    container_name: odontologia_backend
    restart: on-failure

    ports:
      - "8085:8085"

    env_file:
      - .env