services:

  backend:
    build:
      context: .
      dockerfile: DockerFile

    container_name: odontologia_backend
    restart: on-failure

    ports:
      - "8085:8085"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/odonto_house
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin